### ISSUE TITLE
Is there no Display or minimum when you run executable using pypsexec

### ISSUE THREAD

**Issue by prasu5** [jborean93/pypsexec#11]
Whenever I use pypsexec to run selenium scripts on remote windows machine the small display size causes the scripts to fail as elements are not in view(verified by captured screenshot), 
Also when I try to capture screen recording using ffmpeg an opensource tool it gives error
[gdigrab @ 00741500] Failed to capture image (error 5) 
[gdigrab @ 00741500] Could not find codec parameters for stream 0 (Video: bmp, none, 377493 kb/s): unspecified size 
The above both issues are solved when I run the script directly on the windows machine without pypsexec.
Please provide a soloution to this issue

**Comment by jborean93** [comment]
This isn't something that is controlled by pypsexec, you might have some luck with setting the resolution manually then running your tests but honestly I have not played with this before.

**Comment by prasu5** [comment]
> This isn't something that is controlled by pypsexec, you might have some luck with setting the resolution manually then running your tests but honestly I have not played with this before.

Is there no flag which I can set so that each session can have its display

**Comment by jborean93** [comment]
Not that I'm aware of, there might be a command to resize the console during process execution but PAExec doesn't implement an interface to control this. The [Creation of a Console](https://docs.microsoft.com/en-us/windows/console/creation-of-a-console) page shows you how to manage the console attached to a command line process but in this case you are looking at the display. There might be a way to change the display size as part of the script pypsexec runs but nothing is in there natively.

Unfortunately this is down to the end user to implement, this isn't something that is offered in pypsexec.
