### ISSUE TITLE
The system cannot find the file specified

### ISSUE THREAD

**Issue by neoluu** [jborean93/pypsexec#18]
hi,

Im using python on linux and trying to execute an exe on a remote window 2008/2012/2016 server.
The windows domain account im using is part of an AD group that is a member of the server local Administrators group. Login on to the server with the account works and im able to do what i want.

But from my linux server via the python command, Im unable to use dfsutil.exe or dfscmd.exe to create DFS namespace links. I get error: Received exception from remote PAExec service: Failed to start "dfsutil.exe". The system cannot find the file specified. [Err=0x2, 2]

Those files are in C:\windows\system32, just like cmd.exe and cmd.exe works. Evironment variables are proper, I tried copying dfsutil.exe and dfscmd.exe to another directory and set the "working_dir" accordingly but it still does not work. 

Permission on those two files are the same as cmd.exe. When I try "cmd.exe /c dir *.*, that returns file list excluding dfsutil.exe or dfscmd.exe, which is very strange? I also tried with full path to those exe, tried puttting command in a batch file and get the same result, Please advise?

**Comment by jborean93** [comment]
There is an outstanding problem I need to fix where the psexec process is running as a 32-bit process on all systems. This means that `C:\Windows\System32` is in fact `C:\Windows\SysWOW64`. This is why it can’t find the executable as it’s a different folder on a 32-bit process. You can either;

* Make a copy of the executable in another folder that’s in the `PATH` env var
* Use the redirected path to refer to the native System32 from a 32-bit process `C:\Windows\sysnative\dfsutil.exe`

I’m leaving this open to track the progress on. Changing the process architecture to match the host OS in a future release.

**Comment by jborean93** [comment]
Just an FYI, here is the fix for this issue https://github.com/jborean93/pypsexec/pull/22.
