### ISSUE TITLE
Kill process

### ISSUE THREAD

**Issue by xor0x** [jborean93/pypsexec#28]
Hello. I want to kill the process from another PC I'm trying do this
result = c.run_executable("cmd.exe", arguments="taskkill /F /PID 9104") but the process doesn't kill.
Please help.
Sorry for my bad English

**Comment by jborean93** [comment]
When running a cmd task you need to use `cmd.exe` as the executable (which you have done) but also make sure you prefix the actual command to run with `/c` i.e. `cmd.exe /c taskkill /F /PID 9104`. In fact `taskkill` is it's own executable so you can execute that directly without having to go through `cmd.exe` like;

```python
result = c.run_executable("taskkill.exe", arguments="/F /PID 9104")
```

**Comment by xor0x** [comment]
thank you
