### ISSUE TITLE
Connection errors.

### ISSUE THREAD

**Issue by chopraaa** [jborean93/pypsexec#4]
I'm running this to connect to a WS 2012 host:

```
from pypsexec.client import Client

c = Client("genericip", username="genericuser1", password="genericpassword", encrypt=True)
c.connect()
try:
    c.create_service()
    stdout, stderr, rc = c.run_executable("cmd.exe",
                                          arguments="/c echo Hello World")

    stdout, stderr, rc = c.run_executable("whoami.exe", use_system_account=True)

    stdout,stderr, rc = c.run_executable("whoami",
                                          arguments="/all",
                                          username="genericuser2",
                                          password="genericpassword",
                                          run_elevated=True)
finally:
    c.remove_service()
    c.disconnect()
```
When I try connecting using the public IP, I get this:
```
$ python basic.py
Traceback (most recent call last):
  File "basic.py", line 5, in <module>
    c.connect()
  File "/usr/lib/python2.7/site-packages/pypsexec/client.py", line 59, in connect
    self.connection.connect()
  File "/usr/lib/python2.7/site-packages/smbprotocol/connection.py", line 811, in connect
    self.transport.connect()
  File "/usr/lib/python2.7/site-packages/smbprotocol/transport.py", line 58, in connect
    self._sock.connect((self.server, self.port))
  File "/usr/lib64/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 111] Connection refused
```

and this when I connect through a private network; also the script doesn't finish execution:
```
$ python basic.py 
Traceback (most recent call last):
  File "basic.py", line 5, in <module>
    c.connect()
  File "/usr/local/lib/python2.7/dist-packages/pypsexec/client.py", line 63, in connect
    self._service.open()
  File "/usr/local/lib/python2.7/dist-packages/pypsexec/scmr.py", line 207, in open
    DesiredAccess.SC_MANAGER_ENUMERATE_SERVICE
  File "/usr/local/lib/python2.7/dist-packages/pypsexec/scmr.py", line 504, in open_sc_manager_w
    res = self._invoke("ROpenSCManagerW", opnum, data)
  File "/usr/local/lib/python2.7/dist-packages/pypsexec/scmr.py", line 659, in _invoke
    "but got: %s" % (opnum, str(pdu_resp)))
pypsexec.exceptions.PDUException: Expecting ResponsePDU for opnum 15 response but got: FaultPDU:
    rpc_vers = 5
    rpc_vers_minor = 0
    ptype = (3) FAULT
    pfx_flags = (3) PFC_FIRST_FRAG, PFC_LAST_FRAG
    packed_drep =
    DataRepresentationFormat:
        integer_character = (16) ASCII_LITTLE_ENDIAN
        floating_point = (0) IEEE
        reserved1 = 0
        reserved2 = 0

        Raw Hex:
            10 00 00 00
    frag_length = 32
    auth_length = 0
    call_id = 1
    alloc_hint = 32
    p_cont_id = 0
    cancel_count = 0
    reserved = 0
    status = (1783) NCA_S_FAULT_NDR

    Raw Hex:
        05 00 03 03 10 00 00 00
        20 00 00 00 01 00 00 00
        20 00 00 00 00 00 00 00
        F7 06 00 00
```
Firewall's disabled, and SMB's enabled.

```
PS C:\Windows\system32> Get-SmbServerConfiguration | Select EnableSMB2Protocol

EnableSMB2Protocol
------------------
              True
```

**Comment by jborean93** [comment]
For the first point, it sounds like some sort of firewall or service is blocking the connection, is it in AWS or some other service that might block port 445?

The second one is a bit not difficult, I’ve come across it a few times in testing and as you can see from the error it isn’t very helpful. I think the issue stems from how I am packing the server name/ip as a string in the open scmr request but I’ve never been able to replicate it consistently. Looks like I need to look into it a bit further.

The final point I need to find a better solution. As part of the smbconnection setup it creates a thread to listen to SMB responses and it doesn’t close unless it is called. I’ll try and think and see what could be done about that but any suggestions are nice.

**Comment by chopraaa** [comment]
> For the first point, it sounds like some sort of firewall or service is blocking the connection, is it in AWS or some other service that might block port 445?

It's on Google but I've whitelisted every port and protocol so it shouldn't be an issue. I'll troubleshoot it a bit and see if I can reach a conclusion.

Also, the code in the readme has 1-2 typos. 😃

**Comment by chopraaa** [comment]
> For the first point, it sounds like some sort of firewall or service is blocking the connection, is it in AWS or some other service that might block port 445?

It's on Google but I've whitelisted every port and protocol so it shouldn't be an issue. I'll troubleshoot it a bit and see if I can reach a conclusion.

Also, the code in the readme has 1-2 typos. 😃 

**Edit** - 
There's also this:

```
$ python basic.py 
Traceback (most recent call last):
  File "basic.py", line 14, in <module>
    c.remove_service()
  File "/usr/local/lib/python2.7/dist-packages/pypsexec/client.py", line 112, in remove_service
    self._service.refresh()
  File "/usr/local/lib/python2.7/dist-packages/pypsexec/scmr.py", line 258, in refresh
    self.open()
  File "/usr/local/lib/python2.7/dist-packages/pypsexec/scmr.py", line 201, in open
    self._scmr.open()
  File "/usr/local/lib/python2.7/dist-packages/pypsexec/scmr.py", line 327, in open
    self.tree.connect()
  File "/usr/local/lib/python2.7/dist-packages/smbprotocol/tree.py", line 215, in connect
    sid=self.session.session_id)
  File "/usr/local/lib/python2.7/dist-packages/smbprotocol/connection.py", line 920, in send
    self.transport.send(send_data)
  File "/usr/local/lib/python2.7/dist-packages/smbprotocol/transport.py", line 87, in send
    self._sock.sendall(data)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 32] Broken pipe
```

Ran this:
```
from pypsexec.client import Client

server = "x"
username = "x"
password = "x"

c = Client(server, username=username, password=password, encrypt=True)

try:
    c.connect()
    c.create_service()
    result = c.run_executable("hostname.exe")
finally:
    c.remove_service()
    c.disconnect()
print(result)

**Comment by jborean93** [comment]
@chopraaa thanks for the confirmation, so sounds like the socket errors are related to firewall issues and once solve you either get a successful run `('instance-2\r\n', '', 0)` or the PDU exception. I'll start to look into the PDU side to try and solve that issue. I think I know what area is causing it I just don't know the actual cause right now.

I've got some ideas around the socket listener and not running that as a separate thread and will see how I go as well.

Once again thanks for testing all this out, it's great to be able to get this in the hands of others and cover situations like this.

**Comment by jborean93** [comment]
@chopraaa I've just created a `dev2` release for both pypsexec and smbprotocol that contains the fixes you are looking for. You would need to install both of them to get it to work but they fix

* Marshals strings properly when sending it as an RPC request
* Fixed some typos I quickly found on the examples
* The SMB listener no longer runs as a separate thread so quitting the process abruptly should reduce the number of hangs (the exec process still needs this unfortunately)

If you are able to test this hopefully it fixes some of the issues you've come across but let me know if I've missed anything.

**Comment by chopraaa** [comment]
Whoo! Tested it on a bunch of hosts, and it seems to work everywhere. (though to be fair I haven't tested extensively)

I think a note to enable tcp:445 should be added to the README. On my servers, although SMB2 is enabled by default, the firewall doesn't whitelist the port, and hence anything not whitelisted is blocked by default. 

A simple `New-NetFirewallRule -DisplayName "pypsexec" -Direction Inbound  -LocalPort 445 -Action Allow` should be fine I guess..? And if somebody's worried about security, they could just add the control node's IP using `-RemoteAddress <ansible-ip>`.

Also, you missed out a bit in the readme:
```
# set encrypt=False for Windows 7, Server 2008
c = Client("server", username="username", password="password")
```

**Comment by jborean93** [comment]
Of course I screwed up the README further when trying to fix the typos. I plan on making another pass to make it a bit easier to read and understand sometime soon and so will add that information.

Glad to hear that it works for you though, I'll close the ticket as this issue should be resolved.
