### ISSUE TITLE
blank windows when using administrator account

### ISSUE THREAD

**Issue by hepivax** [jborean93/pypsexec#41]
Hi,
When executing applications using the following options I see the app frame but the window content is blank:
`        stdout, stderr, rc = client.run_executable(cmd,
                                                   interactive=True,
                                                   asynchronous=True,
                                                   run_elevated=False,
                                                   interactive_session=1,
                                                   use_system_account=False)`

When I set `use_system_account=True` the problem is solved but this raise another problem as the remote app must run under the administrator account

**Comment by jborean93** [comment]
This is a known problem unfortunately https://github.com/jborean93/pypsexec/issues/40. The PAExec binary doesn't set the proper access rights on the access token so only the SYSTEM account is able to access the interactive desktop. Until I replace PAExec there's nothing I can do to fix this.
