### ISSUE TITLE
Urgent issue -pyinstaller 

### ISSUE THREAD

**Issue by themeswordpress** [jborean93/pypsexec#43]
I got this error when I run my output file from pyinstaller 
My os is Centos

FileNotFoundError: [Errno 2] No such file or directory: '/tmp/_MEIHRBSvn/pypsexec/paexec.exe'

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "mass_deployment.py", line 170, in <module>
  File "pypsexec/client.py", line 166, in remove_service
  File "pypsexec/client.py", line 502, in _delete_file
  File "smbprotocol/open.py", line 1219, in _create_response
  File "smbprotocol/connection.py", line 617, in wrapped
  File "smbprotocol/connection.py", line 931, in receive
smbprotocol.exceptions.SharingViolation: Received unexpected status from the server: A file cannot be opened because the share access flags are incompatible. (3221225539) STATUS_SHARING_VIOLATION: 0xc0000043
[161470] Failed to execute script mass_deployment

**Comment by themeswordpress** [comment]
![Uploading D9683058-1571-4DE5-931C-402F4610A941.png…]()

**Comment by jborean93** [comment]
I don't have any experience with `pyinstaller` so I can't really help you here. The error you have shared shows 2 different exceptions that occur. The first is it was unable to find `paexec.exe` that is [bundled with the package](https://github.com/jborean93/pypsexec/blob/master/pypsexec/paexec.exe). The 2nd is an error when it went to cleanup the host which is a common error I'm unable to fix just at the moment. If you can share more info about `pyinstaller` I might be able to help but if not there's not much else I can do.

**Comment by shreyamalviya** [comment]
I'm facing the same issue on Linux Mint.
@jborean93, what information do you need about pyinstaller? Here's the link if that helps: https://github.com/pyinstaller/pyinstaller.

**Comment by mitchell-bumgarner** [comment]
@themeswordpress I'm not 100% sure what the context will be for Mac or Linux, but on Windows, if you're trying to create the EXE and it gives you that error, you can use the following and it works. It took me a bit to figure out how to include the required files when using pyinstaller, so I hope this helps.

``` bat
pyinstaller --noconfirm --log-level=ERROR ^
    --onefile ^
    --nowindow ^
    --add-data="C:\Program Files\Python39\Lib\site-packages\pypsexec\paexec.exe;pypsexec/" ^
    whatever-filename.py
```

**Comment by jborean93** [comment]
See https://github.com/jborean93/pypsexec/pull/45#issuecomment-899107088
