### ISSUE TITLE
urgent - need help when run exe remotely 

### ISSUE THREAD

**Issue by themeswordpress** [jborean93/pypsexec#44]
Dears Anyone, 

I need your help ASAP!

I am working on a project and this project has a mass deployment feature so I used a pypsexec as part from my project, during my testing I am facing a critical issue that the pypsexec connect to target machine and run my scripts file (powershell) 

i have 3 powershell files , the first powershell file ignore/bypass SSL errors when download from insecure https
the second powershell file for download my agent from server
the thirds and final is to run/execute my exe file (here my issue)

when the last powershell works (it works perfectly) and my application not installed and when I am checking the event windows logs the event said that the application installed successfully !!!

to understand my agent, my agent is exe file after works it will self-extraction so the output is msi file and after my investigation 

the exe already extracted and I can see that the msi generated but not works !!

last thing when go to target machine and run the powershell manually everything works perfectly without any error

**Comment by themeswordpress** [comment]
additional info , i am using a domain user and using same user I tested my feature for 30 machine using same user 

my application installed successfully 100% for 2 - 5 machines only !

and the remain machines just as mentioned above, all my files uploaded to the machine the 3 PowerShell executed but my application not installed!


@jborean93

**Comment by themeswordpress** [comment]
@jborean93

**Comment by jborean93** [comment]
This is not really a bug or issue with this library. You need to enable logging for the installer you are running with to figure out what it is and isn't doing and whether it's reporting an error somewhere. Try to figure out how to run this through PowerShell first then look at how to adapt this for pypsexec.

Also as an FYI please don't mark your issues as urgent, this is a library I maintain in my spare time and there's no guarantee of an SLA or response for these things.
