### ISSUE TITLE
How to copy files to remote windows machine and execute them?

### ISSUE THREAD

**Issue by ukreddy-erwin** [jborean93/pypsexec#46]

**Comment by ukreddy-erwin** [comment]
We can copy that using original psexec.exe command and execute it but not from here using this python module.

 "c:\build\PSEXEC" -i -d -h -u "userName" -p ""password" "\\machine_name" exefile

**Comment by jborean93** [comment]
There's no public way to do this through `pypsexec` but you can easily do this with one of the dependencies [smbprotocol](https://github.com/jborean93/smbprotocol):

```python
import smbclient.shutil

smbclient.shutil.copyfile(
    'source_path',
    '\\\\machine_name\\c$\\path\\file',
    username='userName',
    password='password')
```

**Comment by udayfivekiran** [comment]
yes it works thank you very much.
