### ISSUE TITLE
How to check whether we have access to a particular registry key on windows remote machine?

### ISSUE THREAD

**Issue by ukreddy-erwin** [jborean93/pypsexec#47]

**Comment by jborean93** [comment]
This is really a PowerShell or even general Windows scripting question rather than anything specific to `pypsexec`. This library will help you to run a process but it is up to you to decide what to run.

**Comment by udayfivekiran** [comment]
I am able to write a script using powershell or python to check a registry access in local machine. But to check in the remote machine, is there any function here?
