### ISSUE TITLE
About source code of _openssl.so in pypsexec v0.2.0

### ISSUE THREAD

**Issue by SebastienZHAO** [jborean93/pypsexec#50]
Hi Jordan,
I'm working on one project in which the version of Python is v2.7. So Pypsexec v0.2.0 works for me. Thanks you so much. Furthermore, is it possible to get the source code of _openssl.so? I would like to complement some functionalities into the library and rebuild it.

**Comment by jborean93** [comment]
There is no `_openssl.so` in either the wheel or sdist for this package. I'm not sure what file you are really talking about but it is not affiliated with this project. You might be referring to the native library used by Python itself to interop with OpenSSL but that's not relevant here.
