### ISSUE TITLE
Running Pypsexec connect on windows xp host

### ISSUE THREAD

**Issue by Gaellone** [jborean93/pypsexec#53]
Hi,

I'm trying to use pypsexec to get a connection to a windows XP machine. When i'm launching the connection, I get no response and it times out.

Here's the return error : 
`smbprotocol.exceptions.SMBException: Connection timeout of 5 seconds exceeded while waiting for a message id`

Code i'm using :
`
c = Client(
                    server=fqdn,
                    username=row['login'],
                    password=row['password'],
                    encrypt=False)
                c.connect(timeout=1)
`

It's working fine on W7 machines, and I only have the issue with Windows XP.
Any idea of where it can come from ?

Thanks in advance !

**Comment by ThibautSembeni** [comment]
Hello everyone, 

I have the same issue when I want a connection, on Windows XP.

If you have any solution that's gonna be great !
Thanks

**Comment by jborean93** [comment]
This isn’t possible. Windows XP only has support for SMB v1 and the underling SMB library used here is for SMB v2. There are no plans to support this older version as it is full of security bugs and is only needed for extremely old and out of date Windows hosts.
