### ISSUE TITLE
Help with Replicating PsExec Interactive arguments

### ISSUE THREAD

**Issue by jborean93** [jborean93/pypsexec#7]
I'm trying to find the right syntax to achieve with pypsexec the same result as this psexec command
psexec -s -h -i \\192.168.92.135 -u domain\user -p password cmd

When I use the psexec command it opens a cmd window in the remote computer which can be seen by the user and interact with it 

I have tried several options and combinations, switching true and false values with no success:

This is my code:

```
c= Client(equipo_Remoto, username=user, password=passwd)
c.connect()

try:
	c.create_service()

	c.run_executable(r'cmd.exe', interactive= True, run_elevated= True, use_system_account= True, show_ui_on_win_logon= True, asynchronous= False, load_profile= True)
finally:
	c.remove_service()
	c.disconnect()
```

Thanks

_Originally posted by @kr1shn4murt1 in https://github.com/jborean93/pypsexec/issues/6#issuecomment-422723512_

**Comment by jborean93** [comment]
@kr1shn4murt1 breaking down the flags you have there, the command `psexec -s -h -i \\192.168.92.135 -u domain\user -p password cmd` does the following

* Starts a process on the host `192.168.92.135` calling the executable `cmd.exe`
* The new process is run as the SYSTEM account
* It is interactive with the console session
* It tries to get the highest privileges possible, `-h` but this is moot as you are running as the SYSTEM account

I'm curious as to how that actually works the way you say it does as;

* Setting `-i` without a number afterwards means the process is run in session 0 which is special and not tied to a user logon
* AFAIW PsExec is not able to differentiate between a multiple sessions under the same user, so unless you explicitly specify the session id (see above) then it will default to 0
* This was slightly different on Windows XP and older but this library doesn't work on that so we will ignore it
* I tried this and could not get it to work

The proper way this is meant to be done is by specifying the `interactive_session` kwarg and set the session number you want to display this on. An example of this is;

```
from pypsexec.client import Client

server = "server"
username = "user"
password = "pass"

c = Client(server, username=username, password=password)
c.connect()

try:
    c.create_service()
    c.run_executable('cmd.exe', interactive=True, interactive_session=2,
                     asynchronous=True, use_system_account=True)
finally:
    c.remove_service()
    c.disconnect()
```

I've explicitly set the Session ID to 2 which is the ID of an RDP logon session for a particular user. So this can work but you need to have a way to figure out the session you want to display it on. You can run a previous command like [query session](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/query-session) to get a list of sessions and parse that accordingly but that's outside the scope of this library.

**Comment by ALERTua** [comment]
Hello. I am struggling to get session id and run interactive executables.
I am running Virtualbox Windows 10 virtual machine with logged in user alert.
```
C:\Users\alert>tasklist /FI "IMAGENAME eq tasklist.exe" /NH
tasklist.exe                  1136 Console                    2      9,564 K
```
The user has session id 1.

But run_executeable of the same command returns session id 0.
Whatever I do, run_executeable always returns 0 for my session ids for different users.
```
tasklist.exe                  8964 Services                   0      9,168 K
```
I tried all possible combinations of arguments and had no luck getting non-zero session id.

And the main problem is that if I run_executeable a notepad with interactive=True and interactive_session=1 I do not see the notepad on the target machine's desktop but I can see two notepads in the processes running using session id 0.
![image](https://user-images.githubusercontent.com/8375129/65132578-d8e5a400-da09-11e9-877b-5814f2efe24a.png)

**Comment by jborean93** [comment]
Hmm I don't see that issue at all, I am runnign the following:

```
from pypsexec.client import Client

c = Client("server2019.domain.local")

c.connect()
try:
    c.create_service()

    stdout, stderr, rc = c.run_executable("powershell.exe",
                                          interactive=True,
                                          interactive_session=2,
                                          use_system_account=True,)
finally:
    c.remove_service()
    c.disconnect()
```

Using procmon I can see that the process is running in the session I provided and the actual session can see that as well. The actual PAExec service runs under session 0 because it's spawned by service manager but the process I want to spawn is in the session I specified. Note you do have to run with the SYSTEM account as any other account seems to have troubles actually displaying the Window. The session would be correct but you can't interact with it.

![image](https://user-images.githubusercontent.com/8462645/65188450-ccb52180-dab1-11e9-9aab-6397ed2ef632.png)

**Comment by ALERTua** [comment]
Thank you. I figured out my mistakes and everything works now.
