### ISSUE TITLE
Unable to execute .msi file on remote machine

### ISSUE THREAD

**Issue by TejasSonawan** [jborean93/pypsexec#8]
I am using below script to execute command, However it throwing an exception as "Unknown error value"

Below is exception trace:

  File "C:\Program Files\Python35\lib\site-packages\pypsexec\client.py", line 412, in run_executable
    exe_result.check_resp()
  File "C:\Program Files\Python35\lib\site-packages\pypsexec\paexec.py", line 108, in check_resp
    raise PAExecException(msg_id, self['buffer'].get_value())
pypsexec.exceptions.PAExecException: Received exception from remote PAExec service: Failed to start "myfile.msi". Unknown error value.  [Err=0xC1, 193]

I am using below script:

from pypsexec.client import Client
c = Client("myhost", username="myuser", password="mypass", encrypt=False)

c.connect()
try:
    c.create_service()
    stdout, stderr, rc = c.run_executable("myfile.msi")

    print("\n stdout : " + str(stdout))
    print("\n stderr : " + str(stderr))
    print("\n rc : " + str(rc))

finally:
    c.remove_service()
    c.disconnect()

**Comment by jborean93** [comment]
A MSI is not an executable file in itself, it needs to be called with `msiexec.exe`. The reason why it would when you double click on it or type in the MSI in a shell is that the Windows defaults will run it with msiexec, this is the same behaviour as double clicking on a .txt file and it opening up notepad.

Have a look at http://www.silentinstall.org/msiexec for ways to silently install an MSI file.

**Comment by TejasSonawan** [comment]
Thanks a lot for your quick reply.

**Comment by TejasSonawan** [comment]
I have fixed it with by passing msiexec.exe as executable 
   stdout, stderr, rc = c.run_executable("msiexec.exe",  arguments=path_of_msi_file)
